use bevy::prelude::*;
use crate::player::Player;
use super::{CombatState,DiceRng,Equipment,PlayerStats,Score,HighScores};
use crate::ui::PlayerProfile;

pub fn combat_system(keyboard:Res<ButtonInput<KeyCode>>,mut combat:ResMut<CombatState>,mut rng:ResMut<DiceRng>,equipment:Res<Equipment>,mut score:ResMut<Score>,mut highs:ResMut<HighScores>,profile:Res<PlayerProfile>,player_query:Query<&PlayerStats,With<Player>>){
 if !combat.active||combat.game_over||combat.victory||!combat.rolling||!keyboard.just_pressed(KeyCode::Space){return;} let Ok(stats)=player_query.single() else{return;}; let Some(monster)=combat.monster else{return;}; let Some(weapon)=equipment.weapon else{return;};
 let (monster_max_hp,monster_defense,monster_attack,monster_damage)=monster.stats();
 let (d20,roll_desc)=if combat.first_attack&&combat.surprise!=0{let a=rng.roll(20);let b=rng.roll(20);let chosen=if combat.surprise>0{a.max(b)}else{a.min(b)};(chosen,format!("2D20 = {}/{} -> {}",a,b,chosen))}else{let a=rng.roll(20);(a,format!("D20 = {}",a))}; combat.first_attack=false;
 let attack_total=d20+stats.for_mod();combat.last_roll=Some(d20);
 if d20==20||attack_total>=monster_defense{let damage=weapon.roll_damage(&mut rng)+stats.for_mod().max(0);combat.monster_hp-=damage;if combat.monster_hp<=0{combat.monster_hp=0;combat.rolling=false;combat.victory=true;combat.active=false;score.monsters_killed+=1;highs.update(&profile.name,&score);combat.last_message=format!("Victoire ! {} ; attaque {}. {} inflige {} dégâts. Le {} est vaincu.",roll_desc,attack_total,weapon.name(),damage,monster.name());return;}combat.last_message=format!("Touché ! {} ; attaque {}. {} dégâts ({}). Le {} a {}/{} PV.",roll_desc,attack_total,damage,weapon.damage_label(),monster.name(),combat.monster_hp,monster_max_hp);}else{combat.last_message=format!("Raté ! {} ; attaque {} contre Défense {}.",roll_desc,attack_total,monster_defense);}
 let monster_roll=rng.roll(20);let player_defense=10+stats.dex_mod()+weapon.defense_bonus();if monster_roll>=player_defense{let damage=rng.roll(monster_damage.max(1))+(monster_attack/2);combat.player_hp-=damage;if combat.player_hp<=0{combat.player_hp=0;combat.game_over=true;combat.rolling=false;combat.last_message.push_str(&format!(" Le {} vous touche (D20 {}) : {} dégâts. Vous êtes vaincu.",monster.name(),monster_roll,damage));}else{let current_hp=combat.player_hp; let max_hp=combat.player_max_hp; combat.last_message.push_str(&format!(" Le {} vous touche (D20 {}) : -{} PV. Reste {}/{}.",monster.name(),monster_roll,damage,current_hp,max_hp));}}else{combat.last_message.push_str(&format!(" Le {} rate son attaque (D20 {}).",monster.name(),monster_roll));}
}
